enum TokenType {
    //keywords
    FOR, WHILE, IF, ELIF, NULL, TRUE, FALSE, DEF, ELSE, RETURN,

    //symbols
    OR, AND, EXCLAMATION, EXCLAMATIONEQUALS, LT, LTE, GT, GTE, EQUAL, DOUBLE_EQUAL,
    LEFT_P, RIGHT_P, LEFT_B, RIGHT_B, SEMICOLON, COMMA, DOT, BREAK, CONTINUE,

    //Math
    PLUS, MINUS, SLASH, DOUBLE_SLASH, STAR, DOUBLEPLUS, PLUSEQUALS, DOUBLEMINUS, MINUSEQUALS,

    IDENTIFIER, STRING, NUM, VAR, PRINT, LOGICAL_AND, LOGICAL_OR,

    LEFT_S, RIGHT_S
}
